CREATE USER BANCOMEY IDENTIFIED BY <elegir_una_contraseña>;

-- ---------------------------------
-- 1. CREACION DE TABLAS
-- ---------------------------------

CREATE TABLE SUCURSAL (
    NOMBRE_SUCURSAL   VARCHAR2(50),
    CIUDAD_SUCURSAL   VARCHAR2(50),
    ACTIVO            NUMBER(15,2),
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (NOMBRE_SUCURSAL)
);

CREATE TABLE CLIENTE (
    NOMBRE_CLIENTE    VARCHAR2(50),
    CALLE_CLIENTE     VARCHAR2(100),
    CIUDAD_CLIENTE    VARCHAR2(50),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (NOMBRE_CLIENTE)
);

CREATE TABLE CUENTA (
    NUMERO_CUENTA     NUMBER(10),
    NOMBRE_SUCURSAL   VARCHAR2(50),
    SALDO             NUMBER(15,2),
    CONSTRAINT PK_CUENTA PRIMARY KEY (NUMERO_CUENTA),
    CONSTRAINT FK_CUENTA_SUCURSAL FOREIGN KEY (NOMBRE_SUCURSAL)
        REFERENCES SUCURSAL (NOMBRE_SUCURSAL)
);

CREATE TABLE PRESTAMO (
    NUMERO_PRESTAMO   NUMBER(10),
    NOMBRE_SUCURSAL   VARCHAR2(50),
    IMPORTE           NUMBER(15,2),
    CONSTRAINT PK_PRESTAMO PRIMARY KEY (NUMERO_PRESTAMO),
    CONSTRAINT FK_PRESTAMO_SUCURSAL FOREIGN KEY (NOMBRE_SUCURSAL)
        REFERENCES SUCURSAL (NOMBRE_SUCURSAL)
);

CREATE TABLE IMPOSITOR (
    NOMBRE_CLIENTE    VARCHAR2(50),
    NUMERO_CUENTA     NUMBER(10),
    CONSTRAINT PK_IMPOSITOR PRIMARY KEY (NOMBRE_CLIENTE, NUMERO_CUENTA),
    CONSTRAINT FK_IMPOSITOR_CLIENTE FOREIGN KEY (NOMBRE_CLIENTE)
        REFERENCES CLIENTE (NOMBRE_CLIENTE),
    CONSTRAINT FK_IMPOSITOR_CUENTA FOREIGN KEY (NUMERO_CUENTA)
        REFERENCES CUENTA (NUMERO_CUENTA)
);

CREATE TABLE PRESTATARIO (
    NOMBRE_CLIENTE    VARCHAR2(50),
    NUMERO_PRESTAMO   NUMBER(10),
    CONSTRAINT PK_PRESTATARIO PRIMARY KEY (NOMBRE_CLIENTE, NUMERO_PRESTAMO),
    CONSTRAINT FK_PRESTATARIO_CLIENTE FOREIGN KEY (NOMBRE_CLIENTE)
        REFERENCES CLIENTE (NOMBRE_CLIENTE),
    CONSTRAINT FK_PRESTATARIO_PRESTAMO FOREIGN KEY (NUMERO_PRESTAMO)
        REFERENCES PRESTAMO (NUMERO_PRESTAMO)
);

-- ---------------------------------
-- 2. INSERCION DE DATOS
-- ---------------------------------

-- 2.1 SUCURSAL 

INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Centro La Paz', 'La Paz', 8500000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Sopocachi', 'La Paz', 6200000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Miraflores', 'La Paz', 5400000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('San Pedro', 'La Paz', 4800000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Obrajes', 'La Paz', 7100000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Achumani', 'La Paz', 5900000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Calacoto', 'La Paz', 9200000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Villa Fatima', 'La Paz', 3600000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Munaypata', 'La Paz', 3100000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Zona Sur', 'La Paz', 8700000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Ceja', 'El Alto', 4200000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Rio Seco', 'El Alto', 2800000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Senkata', 'El Alto', 2500000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('16 de Julio', 'El Alto', 3900000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Villa Adela', 'El Alto', 2200000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Equipetrol', 'Santa Cruz', 9800000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Las Palmas', 'Santa Cruz', 6700000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Segundo Anillo', 'Santa Cruz', 5100000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Urbari', 'Santa Cruz', 4400000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Cala Cala', 'Cochabamba', 6300000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Queru Queru', 'Cochabamba', 4900000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Sarco', 'Cochabamba', 3400000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Recoleta', 'Sucre', 5000000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('San Sebastian', 'Sucre', 3200000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Ferroviaria', 'Oruro', 3700000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Central Oruro', 'Oruro', 2900000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('San Cristobal', 'Potosi', 2600000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Centro Potosi', 'Potosi', 3300000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Centro Tarija', 'Tarija', 4100000.00);
INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, CIUDAD_SUCURSAL, ACTIVO) VALUES ('Centro Trinidad', 'Trinidad', 2100000.00);

-- 2.2 CLIENTE 

INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Juan Perez', 'Av. Arce 1245', 'La Paz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Maria Gonzalez', 'Calle Comercio 567', 'La Paz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Carlos Rodriguez', 'Av. 6 de Agosto 890', 'La Paz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Ana Martinez', 'Calle Murillo 234', 'El Alto');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Luis Fernandez', 'Av. Ballivian 456', 'El Alto');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Carmen Lopez', 'Calle Potosi 789', 'El Alto');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Jose Garcia', 'Av. Camacho 321', 'Santa Cruz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Rosa Sanchez', 'Calle Colombia 654', 'Santa Cruz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Pedro Ramirez', 'Av. Montes 987', 'Santa Cruz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Laura Torres', 'Calle Ayacucho 159', 'Cochabamba');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Miguel Flores', 'Av. Saavedra 753', 'Cochabamba');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Patricia Vargas', 'Calle Loayza 246', 'Cochabamba');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Fernando Castro', 'Av. Landaeta 864', 'Sucre');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Gabriela Rojas', 'Calle Yanacocha 135', 'Sucre');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Ricardo Mendoza', 'Av. Ecuador 975', 'Oruro');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Silvia Ortiz', 'Calle Mexico 468', 'Oruro');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Alberto Chavez', 'Av. Villazon 357', 'Potosi');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Veronica Guzman', 'Calle Junin 951', 'Potosi');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Eduardo Quispe', 'Av. Heroes del Pacifico 258', 'Tarija');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Claudia Mamani', 'Calle Illimani 741', 'Tarija');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Roberto Choque', 'Av. Costanera 369', 'Trinidad');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Monica Condori', 'Calle Sagarnaga 852', 'Trinidad');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Diego Apaza', 'Av. Del Ejercito 147', 'Cobija');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Andrea Colque', 'Calle Jaen 963', 'Cobija');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Sergio Yucra', 'Av. Simon Bolivar 258', 'La Paz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Paola Huanca', 'Calle Sucre 741', 'El Alto');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Oscar Ticona', 'Av. Panamericana 369', 'Santa Cruz');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Daniela Callisaya', 'Calle Bolivar 852', 'Cochabamba');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Raul Poma', 'Av. Litoral 147', 'Oruro');
INSERT INTO CLIENTE (NOMBRE_CLIENTE, CALLE_CLIENTE, CIUDAD_CLIENTE) VALUES ('Elena Vega', 'Calle Comercio 963', 'La Paz');

-- 2.3 CUENTA 
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100001, 'Centro La Paz', 15420.50);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100002, 'Sopocachi', 8750.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100003, 'Miraflores', 23100.75);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100004, 'San Pedro', 4500.25);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100005, 'Obrajes', 31200.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100006, 'Achumani', 9800.60);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100007, 'Calacoto', 45600.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100008, 'Villa Fatima', 2300.15);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100009, 'Munaypata', 6700.40);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100010, 'Zona Sur', 18900.90);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100011, 'Ceja', 3200.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100012, 'Rio Seco', 5400.35);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100013, 'Senkata', 1200.80);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100014, '16 de Julio', 7600.20);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100015, 'Villa Adela', 2900.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100016, 'Equipetrol', 52000.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100017, 'Las Palmas', 27300.45);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100018, 'Segundo Anillo', 14800.60);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100019, 'Urbari', 9200.10);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100020, 'Cala Cala', 16700.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100021, 'Queru Queru', 8300.25);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100022, 'Sarco', 4100.50);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100023, 'Recoleta', 12500.75);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100024, 'San Sebastian', 6900.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100025, 'Ferroviaria', 3800.40);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100026, 'Central Oruro', 5600.20);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100027, 'San Cristobal', 2700.00);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100028, 'Centro Potosi', 9100.65);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100029, 'Centro Tarija', 13400.30);
INSERT INTO CUENTA (NUMERO_CUENTA, NOMBRE_SUCURSAL, SALDO) VALUES (100030, 'Centro Trinidad', 4700.00);

-- 2.4 PRESTAMO 
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200001, 'Centro La Paz', 85000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200002, 'Sopocachi', 45000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200003, 'Miraflores', 120000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200004, 'San Pedro', 25000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200005, 'Obrajes', 95000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200006, 'Achumani', 60000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200007, 'Calacoto', 150000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200008, 'Villa Fatima', 18000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200009, 'Munaypata', 22000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200010, 'Zona Sur', 110000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200011, 'Ceja', 30000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200012, 'Rio Seco', 15000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200013, 'Senkata', 12000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200014, '16 de Julio', 40000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200015, 'Villa Adela', 20000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200016, 'Equipetrol', 200000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200017, 'Las Palmas', 75000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200018, 'Segundo Anillo', 55000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200019, 'Urbari', 35000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200020, 'Cala Cala', 65000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200021, 'Queru Queru', 28000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200022, 'Sarco', 17000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200023, 'Recoleta', 48000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200024, 'San Sebastian', 26000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200025, 'Ferroviaria', 19000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200026, 'Central Oruro', 23000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200027, 'San Cristobal', 14000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200028, 'Centro Potosi', 32000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200029, 'Centro Tarija', 41000.00);
INSERT INTO PRESTAMO (NUMERO_PRESTAMO, NOMBRE_SUCURSAL, IMPORTE) VALUES (200030, 'Centro Trinidad', 16000.00);

-- 2.5 IMPOSITOR 

INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Juan Perez', 100001);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Maria Gonzalez', 100002);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Carlos Rodriguez', 100003);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Ana Martinez', 100004);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Luis Fernandez', 100005);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Carmen Lopez', 100006);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Jose Garcia', 100007);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Rosa Sanchez', 100008);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Pedro Ramirez', 100009);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Laura Torres', 100010);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Miguel Flores', 100011);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Patricia Vargas', 100012);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Fernando Castro', 100013);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Gabriela Rojas', 100014);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Ricardo Mendoza', 100015);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Silvia Ortiz', 100016);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Alberto Chavez', 100017);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Veronica Guzman', 100018);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Eduardo Quispe', 100019);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Claudia Mamani', 100020);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Roberto Choque', 100021);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Monica Condori', 100022);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Diego Apaza', 100023);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Andrea Colque', 100024);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Sergio Yucra', 100025);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Paola Huanca', 100026);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Oscar Ticona', 100027);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Daniela Callisaya', 100028);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Raul Poma', 100029);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Elena Vega', 100030);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Juan Perez', 100016);
INSERT INTO IMPOSITOR (NOMBRE_CLIENTE, NUMERO_CUENTA) VALUES ('Maria Gonzalez', 100030);

-- 2.6 PRESTATARIO 
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Juan Perez', 200001);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Maria Gonzalez', 200002);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Carlos Rodriguez', 200003);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Ana Martinez', 200004);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Luis Fernandez', 200005);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Carmen Lopez', 200006);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Jose Garcia', 200007);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Rosa Sanchez', 200008);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Pedro Ramirez', 200009);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Laura Torres', 200010);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Miguel Flores', 200011);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Patricia Vargas', 200012);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Fernando Castro', 200013);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Gabriela Rojas', 200014);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Ricardo Mendoza', 200015);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Silvia Ortiz', 200016);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Alberto Chavez', 200017);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Veronica Guzman', 200018);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Eduardo Quispe', 200019);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Claudia Mamani', 200020);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Roberto Choque', 200021);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Monica Condori', 200022);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Diego Apaza', 200023);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Andrea Colque', 200024);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Sergio Yucra', 200025);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Paola Huanca', 200026);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Oscar Ticona', 200027);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Daniela Callisaya', 200028);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Raul Poma', 200029);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Elena Vega', 200030);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Carlos Rodriguez', 200016);
INSERT INTO PRESTATARIO (NOMBRE_CLIENTE, NUMERO_PRESTAMO) VALUES ('Fernando Castro', 200025);

COMMIT;

