CREATE USER BANCOMEY;

CREATE TABLE "BANCOMEY"."CLIENTE" 
   (	"NOMBRE_CLIENTE" VARCHAR2(30), 
	"CALLE_CLIENTE" VARCHAR2(30), 
	"CIUDAD_CLIENTE" VARCHAR2(20), 
	 PRIMARY KEY ("NOMBRE_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "BANCOMEY"."CUENTA" 
   (	"NUMERO_CUENTA" NUMBER, 
	"NOMBRE_SUCURSAL" VARCHAR2(30), 
	"SALDO" NUMBER, 
	 PRIMARY KEY ("NUMERO_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "BANCOMEY"."IMPOSITOR" 
   (	"NOMBRE_CLIENTE" VARCHAR2(30), 
	"NUMERO_CUENTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "BANCOMEY"."IMPOSITOR_PK0" ON "BANCOMEY"."IMPOSITOR" ("NOMBRE_CLIENTE", "NUMERO_CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "BANCOMEY"."IMPOSITOR" ADD CONSTRAINT "IMPOSITOR_PK0" PRIMARY KEY ("NOMBRE_CLIENTE", "NUMERO_CUENTA")
  USING INDEX "BANCOMEY"."IMPOSITOR_PK0"  ENABLE;

ALTER TABLE "BANCOMEY"."IMPOSITOR" ADD CONSTRAINT "IMPOSITOR_FK1" FOREIGN KEY ("NOMBRE_CLIENTE")
	  REFERENCES "BANCOMEY"."CLIENTE" ("NOMBRE_CLIENTE") ENABLE NOVALIDATE;
  ALTER TABLE "BANCOMEY"."IMPOSITOR" ADD CONSTRAINT "IMPOSITOR_FK02" FOREIGN KEY ("NUMERO_CUENTA")
	  REFERENCES "BANCOMEY"."CUENTA" ("NUMERO_CUENTA") ENABLE NOVALIDATE;
;

CREATE TABLE "BANCOMEY"."PRESTAMO" 
   (	"NUMERO_PRESTAMO" NUMBER, 
	"NOMBRE_SUCURSAL" VARCHAR2(20), 
	"IMPORTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "BANCOMEY"."PRESTAMO_PK0" ON "BANCOMEY"."PRESTAMO" ("NUMERO_PRESTAMO", "NOMBRE_SUCURSAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "BANCOMEY"."PRESTAMO" ADD CONSTRAINT "PRESTAMO_PK0" PRIMARY KEY ("NUMERO_PRESTAMO", "NOMBRE_SUCURSAL")
  USING INDEX "BANCOMEY"."PRESTAMO_PK0"  ENABLE;

ALTER TABLE "BANCOMEY"."PRESTAMO" ADD CONSTRAINT "PRESTAMO_FK0" FOREIGN KEY ("NOMBRE_SUCURSAL")
	  REFERENCES "BANCOMEY"."SUCURSAL" ("NOMBRE_SUCURSAL") ENABLE NOVALIDATE;
;

CREATE TABLE "BANCOMEY"."PRESTATARIO" 
   (	"NOMBRE_CLIENTE" VARCHAR2(30), 
	"NUMERO_PRESTAMO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "BANCOMEY"."PRESTATARIO_PK0" ON "BANCOMEY"."PRESTATARIO" ("NOMBRE_CLIENTE", "NUMERO_PRESTAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "BANCOMEY"."PRESTATARIO" ADD CONSTRAINT "PRESTATARIO_PK0" PRIMARY KEY ("NOMBRE_CLIENTE", "NUMERO_PRESTAMO")
  USING INDEX "BANCOMEY"."PRESTATARIO_PK0"  ENABLE;

ALTER TABLE "BANCOMEY"."PRESTATARIO" ADD CONSTRAINT "PRESTATARIO_FK1" FOREIGN KEY ("NOMBRE_CLIENTE")
	  REFERENCES "BANCOMEY"."CLIENTE" ("NOMBRE_CLIENTE") ENABLE NOVALIDATE;
;

CREATE TABLE "BANCOMEY"."SUCURSAL" 
   (	"NOMBRE_SUCURSAL" VARCHAR2(20), 
	"CIUDAD_SUCURSAL" VARCHAR2(20), 
	"ACTIVO" NUMBER, 
	 PRIMARY KEY ("NOMBRE_SUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;